apiVersion: v1
kind: Pod
metadata:
  name: connector-manager
spec:
  containers:
  - name: connector-manager
    image: curlimages/curl:7.73.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always