#This is not working
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: kafka-connect
data:
  dockerconfigjson: L2hvbWUvYWxiZXJ0by8uZG9ja2VyL2NvbmZpZy5qc29uCg==
type: kubernetes.io/dockerconfigjson